apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po-secret
spec:
  containers:
    -
      args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
      command:
        - /usr/bin/php
      env:
        -
          name: author
          value: Patricia
      image: patrabas/phpinfo:latest
      livenessProbe:
        tcpSocket:
          port: 8080
      name: phpinfo-container
      ports:
        -
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /index.php
          port: 8080
      resources:
        limits:
          cpu: 100m
          memory: 100M
        requests:
          cpu: 100m
          memory: 100M
      volumeMounts:
        -
          mountPath: /app/index.php
          name: public
          readOnly: true
          subPath: index.php
      workingDir: /app/
  volumes:
    -
      ## wget https://raw.githubusercontent.com/patrabas/phpinfo/2021-09-Santander/src/index.php
      ## kubectl create -n gca-phpinfo-github secret generic index.php --from-file index.php
      secret:
        defaultMode: 0400
        items:
          -
            key: index.php
            mode: 0400
            path: index.php
        secretName: index.php
      name: public
status: {}
